"""SQLModel table definitions.

Each class here serves double duty:
  - As a SQLAlchemy ORM table (table=True)
  - As a Pydantic model for type-safe access

The schemas in app/schemas/ extend these for request/response shapes.
"""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, ClassVar, Optional

from sqlalchemy import JSON
from sqlmodel import Column, DateTime, Field, Relationship, SQLModel, func, text

if TYPE_CHECKING:
    # Expose __tablename__ as ClassVar[str] to type checkers only.
    # At runtime SQLModel expects a plain string assignment; pyright sees the
    # declared_attr base type and complains about mutability. This block
    # satisfies both without changing runtime behaviour.
    from typing import Any
    declared_attr = ClassVar[Any]


class User(SQLModel, table=True):
    """Registered user account.

    Attributes:
        id: UUID primary key, generated by the database.
        email: Unique email address used for authentication.
        full_name: Optional display name.
        hashed_password: bcrypt hash — never the plain-text password.
        language: Preferred Hover AI language code (e.g. ``"en-pidgin"``).
        created_at: UTC timestamp set on insert.
        settings: Back-populated one-to-one relationship to UserSettings.
    """

    __tablename__ = "users"  # type: ignore[assignment]

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    email: str = Field(unique=True, index=True, max_length=320)
    full_name: Optional[str] = Field(default=None, max_length=120)
    hashed_password: str
    language: str = Field(default="en-pidgin", max_length=20)
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(DateTime(timezone=True), server_default=func.now(), nullable=False),
    )

    settings: Optional["UserSettings"] = Relationship(back_populates="user")
    query_logs: list["QueryLog"] = Relationship(back_populates="user")
    refresh_tokens: list["RefreshToken"] = Relationship(back_populates="user")


class UserSettings(SQLModel, table=True):
    """Per-user application settings.

    Mirrors ``AppSettings`` in ``hover-app/src/preload/index.d.ts`` exactly.
    Keep both in sync when adding new settings fields.

    Attributes:
        user_id: FK to users.id — also the primary key (one-to-one).
        overlay_opacity: Overlay window opacity (0.4–1.0).
        overlay_size: Widget size variant.
        mic_sensitivity: Microphone sensitivity level (1–10).
        sound_effects: Whether UI sound effects are enabled.
        notifications: Whether desktop notifications are enabled.
        wake_word_enabled: Whether wake-word detection is active.
        launch_at_login: Whether the app launches at system login.
        show_in_taskbar: Whether the app appears in the system taskbar.
        updated_at: UTC timestamp updated on every PATCH.
    """

    __tablename__ = "user_settings"  # type: ignore[assignment]

    user_id: uuid.UUID = Field(foreign_key="users.id", primary_key=True)
    overlay_opacity: float = Field(default=1.0)
    overlay_size: str = Field(default="default", max_length=20)
    mic_sensitivity: int = Field(default=5)
    sound_effects: bool = Field(default=True)
    notifications: bool = Field(default=True)
    wake_word_enabled: bool = Field(default=False)
    launch_at_login: bool = Field(default=False)
    show_in_taskbar: bool = Field(default=False)
    voice_gender: str = Field(default="female", max_length=10)  # "female" | "male"
    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(
            DateTime(timezone=True),
            server_default=func.now(),
            onupdate=func.now(),
            nullable=False,
        ),
    )

    user: Optional[User] = Relationship(back_populates="settings")


class RefreshToken(SQLModel, table=True):
    """Opaque refresh token stored in the database.

    Issued alongside every access token. Allows the client to obtain a new
    short-lived access token without re-authenticating. Only one active token
    per device (``device_id``) is kept; signing in from a new device does not
    invalidate existing sessions.

    Attributes:
        id: UUID primary key.
        user_id: FK to users.id. Cascade-deleted when the user is removed.
        token: Cryptographically random 64-byte hex string (128 chars).
        device_id: Optional client-supplied identifier (e.g. "electron-mac").
        expires_at: Absolute expiry — enforced server-side on every refresh call.
        revoked: Set to True on sign-out or token rotation. Revoked tokens are
            rejected immediately even if not yet expired.
        created_at: UTC timestamp of issuance.
    """

    __tablename__ = "refresh_tokens"  # type: ignore[assignment]

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    user_id: uuid.UUID = Field(foreign_key="users.id")
    token: str = Field(max_length=128, unique=True, index=True)
    device_id: Optional[str] = Field(default=None, max_length=120)
    expires_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), nullable=False)
    )
    revoked: bool = Field(default=False)
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(DateTime(timezone=True), server_default=func.now(), nullable=False),
    )

    user: Optional[User] = Relationship(back_populates="refresh_tokens")


class QueryLog(SQLModel, table=True):
    """Benchmark log entry written by every POST /api/v1/query call.

    Stores the transcript and latency from all three STT engines so the
    hackathon benchmark report can be generated from the database without
    re-running inference.

    Attributes:
        id: UUID primary key.
        user_id: FK to users.id (nullable — set NULL if user is deleted).
        created_at: UTC timestamp of the query.
        language_used: Hover AI language code used for this query.
        audio_duration_ms: Duration of the audio clip in milliseconds.
        transcript_sahara: Intron Sahara primary transcript.
        sahara_latency_ms: Sahara end-to-end latency (upload + polling).
        transcript_whisper: Groq whisper-large-v3-turbo transcript.
        whisper_latency_ms: Groq Whisper round-trip latency.
        transcript_afrispeech: HF afrispeech-whisper-medium-all transcript.
        afrispeech_latency_ms: HF AfriSpeech round-trip latency.
        vision_response: Raw vision LLM JSON response (stored as text).
        beacon_steps: Parsed BeaconStep list JSON (stored as text).
    """

    __tablename__ = "query_logs"  # type: ignore[assignment]

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    user_id: Optional[uuid.UUID] = Field(default=None, foreign_key="users.id")
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(DateTime(timezone=True), server_default=func.now(), nullable=False),
    )
    language_used: str = Field(max_length=20)
    audio_duration_ms: Optional[int] = Field(default=None)

    # Intron Sahara — primary STT
    transcript_sahara: Optional[str] = Field(default=None)
    sahara_latency_ms: Optional[int] = Field(default=None)

    # Groq whisper-large-v3-turbo — benchmark #2
    transcript_whisper: Optional[str] = Field(default=None)
    whisper_latency_ms: Optional[int] = Field(default=None)

    # HuggingFace afrispeech-whisper-medium-all — benchmark #3
    transcript_afrispeech: Optional[str] = Field(default=None)
    afrispeech_latency_ms: Optional[int] = Field(default=None)

    # Vision LLM output — stored as JSONB in PostgreSQL (text in SQLite tests)
    vision_response: Optional[str] = Field(
        default=None, sa_column=Column(JSON, nullable=True)
    )
    beacon_steps: Optional[str] = Field(
        default=None, sa_column=Column(JSON, nullable=True)
    )

    user: Optional[User] = Relationship(back_populates="query_logs")
